# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Iain-S.github.io/nbdev_mre/"

git_url = "https://github.com/Iain-S/nbdev_mre/tree/main/"

def custom_doc_links(name): return None
